platform :ios, "9.0"

use_frameworks!
inhibit_all_warnings!

target "CaseIterable_Example" do
  pod "CaseIterable", :path => "../"
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "nuomi1"
end
