platform :ios, "10.3"

use_frameworks!
inhibit_all_warnings!

target "CaseIterable_Example" do
  pod "CaseIterable", :path => "../"

  target "CaseIterable_Tests" do
    pod "DeviceKit"
    pod "Moya"

    inherit! :complete
  end
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "nuomi1"
end
