platform :ios, "11.4"

use_frameworks! :linkage => :static

target "CaseIterable_Example" do
  pod "CaseIterable", :path => "../"

  target "CaseIterable_Tests" do
    pod "DeviceKit"

    inherit! :complete
  end
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "nuomi1"
end
