name: CaseIterable

attributes:
  ORGANIZATIONNAME: nuomi1

targets:
  CaseIterable_Example:
    type: application
    platform: iOS
    deploymentTarget: 11.4
    sources:
      - CaseIterable
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.cocoapods.demo.CaseIterable-Example
        SWIFT_VERSION: 5.0
    scheme:
      testTargets:
        - CaseIterable_Tests
      environmentVariables:
        ASSETS_DIRECTORY: ${ASSETS_DIRECTORY}

  CaseIterable_Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 11.4
    sources:
      - Tests
