name: CaseIterable

attributes:
  ORGANIZATIONNAME: nuomi1

targets:
  CaseIterable_Example:
    type: application
    platform: iOS
    deploymentTarget: 10.3
    sources:
      - CaseIterable
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.cocoapods.demo.CaseIterable-Example
        SWIFT_VERSION: 5.0

  CaseIterable_Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 10.3
    sources:
      - Tests
