# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ENV["ASSETS_DIRECTORY"] ||= ENV["PWD"] + "/CaseIterable/Assets/"
    ENV["FL_COCOAPODS_PODFILE"] ||= "Example/Podfile"
    ENV["XCODEGEN_SPEC"] ||= "Example/project.yml"
    ENV["GITHUB_GIST_TOKEN"] ||= "CUSTOM_GITHUB_GIST_TOKEN"
    ENV["GITHUB_GIST_ID"] ||= "CUSTOM_GITHUB_GIST_ID"
  end

  lane :setup_xcodegen do
    xcodegen
  end

  lane :setup_cocoapods do
    cocoapods
  end

  lane :setup do
    setup_xcodegen
    setup_cocoapods
  end

  lane :scan_test do |options|
    scan(
      workspace: "Example/CaseIterable.xcworkspace",
      clean: true,
      destination: [
        "platform=iOS Simulator,OS=10.3.1,name=iPhone 6s",
        "platform=iOS Simulator,OS=11.0.1,name=iPhone 6s",
        "platform=iOS Simulator,OS=11.1,name=iPhone 6s",
        "platform=iOS Simulator,OS=11.2,name=iPhone 6s",
        "platform=iOS Simulator,OS=11.3,name=iPhone 6s",
        "platform=iOS Simulator,OS=11.4,name=iPhone 6s",
        "platform=iOS Simulator,OS=12.0,name=iPhone 6s",
        "platform=iOS Simulator,OS=12.1,name=iPhone 6s",
        "platform=iOS Simulator,OS=12.2,name=iPhone 6s",
        "platform=iOS Simulator,OS=12.4,name=iPhone 6s",
        "platform=iOS Simulator,OS=13.0,name=iPhone 6s",
        "platform=iOS Simulator,OS=13.1,name=iPhone 6s",
        "platform=iOS Simulator,OS=13.2.2,name=iPhone 6s",
        "platform=iOS Simulator,OS=13.3,name=iPhone 6s",
        "platform=iOS Simulator,OS=13.4,name=iPhone 6s",
      ],
      max_concurrent_simulators: 2,
    )
  end

  lane :generate_json do
    setup
    scan_test()
  end

  lane :generate_swift do
    sh("./run-gyb.sh")
  end
end
